server:
   port: 8040 #端口
spring:
   application:
      name: cdqt-module-docs #应用名称
   servlet:
      multipart:
         enabled: true #是否开启批量上传
         max-file-size: 128MB #单个文件最大大小
         max-request-size: 1024MB #上传总数据量大小
   jackson: #jackson时间序列化配置
      default-property-inclusion: always #序列化参数
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
   mvc: #spring mvc 时间序列化配置
      date-format: yyyy-MM-dd HH:mm:ss
info:
   version: '@project.version@'
   groupId: '@project.groupId@'
   artifactId: '@project.artifactId@'