server:
   port: 8001
spring:
   application:
      name: cdqt-module-mongo
   servlet:
      multipart:
         enabled: true #是否开启批量上传
         max-file-size: 128MB #单个文件最大大小
         max-request-size: 1024MB #上传总数据量大小
   data:
      mongodb:
         uri: mongodb://night:123456@192.168.1.4:27017/night #配置MongoDB连接
         bucket: night
management: #跨域设置
   endpoints:
      web:
         exposure:
            include: '*'
         cors:
            allowed-origins: '*'
            allowed-methods: '*'
eureka: #注册中心设置
   instance:
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
   client:
      healthcheck:
         enabled: true
      service-url:
         defaultZone: http://admin:123456@localhost:8761/eureka/
file:
   account: admin
   password: 123456
   key: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAM2LByqLGehhXHFoLsZoWmfNo5U4srzPcjoZPeCGNhSCKpzYjpDnsHJe4rQfHvSj/mIq4SB9oSuDDD5Hz33pjkniYofuh4TDhGZojTK8BLAb9grHwLYDCVhcuvaMZfInGJUTamWKDPUZAjfP0oA8pqaRFf0o9ouG6gwUVyHOc2ctAgMBAAECgYAjDrV4MiWHFyQXS7e+q4nP7qkaCIOj5JYNBsUhCIMs2E7AVcdrO7lCqKBuLGixPU9kGwAu9H6K1109Oi5PwYg9D5li5GqFgxu3I39o9HdN27y+V9Sk49KPN+RkF8nzbEWurOVnTDA0oUirJvWSR1rA9JB4KWS3SfJhi5FaBwzL2QJBAObOFKOMv900s1BAoV6htRtzNNQrOzf0do95vXpPEh/lwVs57NiIeuC+iQmhVtA8RfPbEOhbkRoarDmnS+rKR3sCQQDj+v6uBZShZMOOgd+lqOqIz45Yprs6rGDxrZidPd9hum6GToO92aeT45NM1wlW3Sfg2bWoJhH0CCM16Izp9nd3AkAl7BZYCPg9UDtmJDhfZBJtwDAd7Dx+pRwV1trbDcLcmtN6ObpAmawW4TeC7Y9mB4E23/eXNfRRZbCGiIZgvXuhAkBCQ81M9bBK7QfuXw+LjjqFg5bDa8sV9c7D0IqAgeBw/ohrn1ypjR8pXEePWR2M0wFpWL51XoNvZAIgBDUZOBtnAkAR3tmLj/oKyOj9A9dKY9yVETnvu3UXJQ+kQn8uG42YsBs/1BW9jho6q3ibTc2pODvMGm2buvNwsyr/3zA00IMb
info:
   version: '@project.version@'
   groupId: '@project.groupId@'
   artifactId: '@project.artifactId@'