server:
   port: 8001
spring:
   application:
      name: cdqt-module-mongo
   servlet:
      multipart:
         enabled: true #是否开启批量上传
         max-file-size: 12800MB #单个文件最大大小
         max-request-size: 102400MB #上传总数据量大小
   data:
      mongodb:
         uri: mongodb://night:123456@192.168.1.4:27017/night #配置MongoDB连接
         bucket: night
management: #跨域设置
   endpoints:
      web:
         exposure:
            include: '*'
         cors:
            allowed-origins: '*'
            allowed-methods: '*'
eureka: #注册中心设置
   instance:
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
   client:
      healthcheck:
         enabled: true
      service-url:
         defaultZone: http://admin:123456@localhost:8761/eureka/
file:
   account: admin
   password: come564
   key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAL5Ge+vkBM4jOP4E73lnLaIY6bXEjUjetlvYCeRFQRckePSDVveOdQKqer7V0fY09z1dkQCsAfXIqAQG2oAYuCiaQiMorJQSchV96uVn/vMZ/hPSj+AXgMbvypLe8oRYERazyyN7r8dfbefKJozWe6xODzTHRlhPE/XeRPOz2aZFAgMBAAECgYBj0D+zh8LJjAqanmYtTmXO0bjP5FKlNkd9OIA/4eB6TmSxB7D4Xh+djWakczAYMsK7yziEnLbOgzs4GYxHhDAeHJB/Qz/OY44DvDK5YYWutmOhOUykmOcMH0Vp1KPcC6ksEzNkL7PKvbyn/d0/1VxTj1ZqRjPCwAMZtGhS8LAygQJBAOob8kWXSJzUcqXBHZ+8Vm0NHxBpjzW2XSfoe5WHqbkpTz9Hxv2t84mZxN+YgblBC+gm0ld1olZZkTuvEojg+OECQQDQEUDB2W+QermmsXyhnOXfiXnsSjVZO9JgyoefdJqKX8AJJbowjL6MrBWNskW+HWhOioaEeKo1PRwDkx8ucqXlAkEA6exkx+6jirmpmUB+5ladkTfUO2UOyR/gs3jUzBQTnkXNvrBtAJxpRawVkUplDQQW7rCj6upK/LdgrF+CSK1rYQJAViBOJe/TdoLWhmHBrUQ9AyLtDRpKqv1QQDCVozOpJM4tt5ueTqpz1dcFtPmuVNvnaVt+AyfPjOoWxoQHzDo44QJBAJdpgXctK32eqkkLF/S3HNdDNna7lOD52G5QZ/26YasVdziWspW7QfCon1LoLJudufPman3aEc1gKkkTdmyaQnc=
info:
   version: '@project.version@'
   groupId: '@project.groupId@'
   artifactId: '@project.artifactId@'